var GAME_LEVELS = [
/*["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                                                ",
   "                                                                                ",
   "                           x                                                    ",
   "                           x                                                    ",
   "                           x                                                    ",
   "                           x                                                    ",
   "                           x                                                   o",
   "      t           g        x          c              l              w          x",
   "                           x                                                  xx",
   "  @                   p    x          o              !                       xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],*/
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                     x!!!!!!!!!!",
   "     s                                                               x!!!!!!!!!!",
   "    xxx                                                              x!!!!!!!!!!",
   "                                                                     x!!!!!!!!!!",
   "s          s                                                       s x!!!!!!!!!!",
   "x       !          !                                              xxx!!xxxxxxxxx",
   "        x=         x                               xx    = xxxxxxxx!!!x         ",
   "              s                              xx                  x!!!x          ",
   "    x                    x                                       xx!xx          ",
   "   xx                   xx==       xxxxx                          xvxx      x sx",
   "                         x                                           xs      xxx",
   "x              xxxx      x               x   x                       xx      x  ",
   "                         x                                                   x  ",
   " s                       xx               xxx    x                          xx  ",
   "xxxxxxxxxxxxxxxxxx       x               |   |                               x  ",
   "                         x                 s               =     xxxxx       x  ",
   " s                       xxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "xxxxx            xxxx         x   x                  x     x                    ",
   "    x  o         x          s=!!!!x                  x!!!!!x                    ",
   "    xxxxx                xxxxxx!!!x                  x!!!!!x                    ",
   "           x            x     xxxxx                  xxxxxxx                    ",
   "  @        x    s      x                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                                                       "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                s      x!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                      xxxxxxxxxxxxxx   xxxxxxxxxx!!x         x                                    s   s   s  x!x  ",
   "                      !        xxxxx            xx!x         x     s   s                                    xx!x  ",
   "                      !         xxx              x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                      !          x               xvx         x     x   x                   !!!!!!!!!!!!!!!!!!!xx  ",
   "                      !                                      xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                      !                                       xx!!!!!!!!!!!xx            v                        ",
   "                      !                                        xxxx!!!!!xxxx                                      ",
   "                      !                        x     x            xxxxxxx        xxx         xxx                  ",
   "                      !                        x  v  x                           x x         x x                  ",
   "                      x                        x     x                             x     v   x                    ",
   "   p                  x                        x     x                             xx        x                    ",
   "xxxxxxxxx             x                        xx    x                             x         x                    ",
   "                  o   x                        x  v  x      s  s     x   x         x         x                    ",
   "               xxxxxxxx       xxx   xxx        x     x               x   x         x     v   x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x s x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx s xx         x     x               x     s     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  s s  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    s                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "x                                     x   x           x                    x!!!x                              ",
   "x                                     x   x           x                     xxx                               ",
   "x                                    xx   xx          x                                                       ",
   "x                                     x   x= = = =    x            xxx                                        ",
   "xx         xxxxxxxxxxxxx              x   x           x           x!!!x                                       ",
   "                    =  x              x   x    = = = =x     o      xxx       xxx                              ",
   " o                     xxxxxxxxxxxxxxxx   xx          x                     x!!!x                             ",
   "                                      x   x           x     x                xxv        xxx                   ",
   "xxxxxxxxxxxxxxxx                     ox   x           x              x                 x!!!x                  ",
   "!!!!!!!!!!!!!!!!                     xxxxxxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "vxxxxxxxxxxxxxxv                           x          x!!!!!!!!!!!!!!x                                        ",
   "         x          xx                   o x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "  o      xo        x!!xx   xxxxxxxxxxxxxxxxx                                         xxx                      ",
   "xxxxx    xx        x!!xx                  x                                         x!!!x                xxx  ",
   "x        x         x!!xxo                 x                                          xxx                 x x  ",
   "x        x         x!xxxx                 xxxxxxx                        xxxxx                             x  ",
   "x      xxxxxxxxxxxxx!xxxxxxxx!!xxxxxx     x                              x   x                             x  ",
   "xx                                       xx                              x x x                             x  ",
   "  xx                                      x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                                o o    x                              x         xxx                     x  ",
   "  x o            =xxxxx=      xx          x                             xxx       x!!!x          x         x  ",
   "  xxxxx           ox!xo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
