var GAME_LEVELS = [
  /*["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
   "                                                                                ",
   "                                                                                ",
   "                           x                                                    ",
   "                           x                                                    ",
   "                           x      c                                             ",
   "               g           x                                                    ",
   "                           x                     l                             o",
   "    t                      x                                          w        x",
   "                           x                                                  xx",
   "  @                   p    x          o              !                       xxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],   
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                     x!!!!!!!!!!",
   "     o                                                               x!!!!!!!!!!",
   "    xxx                                                              x!!!!!!!!!!",
   "                                                                     x!!!!!!!!!!",
   "o          o                                                       o x!!!!!!!!!!",
   "x       !          !                                              xxx!!xxxxxxxxx",
   "        x=         x                               xx    = xxxxxxxx!!!x         ",
   "              o                              xx                  x!!!x          ",
   "    x                    x                                       xx!xx          ",
   "   xx                   xx==       xxxxx                          xvxx      x ox",
   "                         x                                           xo      xxx",
   "x              xxxx      x               x   x                       xx      x  ",
   "                         x                                                   x  ",
   " o                       xx               xxx    x                          xx  ",
   "xxxxxxxxxxxxxxxxxx       x               |   |                               x  ",
   "                         x                 o               =     xxxxx       x  ",
   " o                       xxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "xxxxx            xxxx         x   x                  x     x                    ",
   "    x  o         x          o=!!!!x                  x!!!!!x                    ",
   "    xxxxx         x      xxxxxx!!!x                  x!!!!!x                    ",
   "           x            x     xxxxx                  xxxxxxx                    ",
   "  @        x    o      x                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                                                       "],
  ["                                      x!!x                   xxxxxxxxxxxx                                    x!x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!x                   xxxxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxxxxxxxxxxxxxxx           xx                                x!x  ",
   "                                o      x!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                      xxxxxxxxxxxxxx   xxxxxxxxxx!!x                        xx                    o   o   o  x!x  ",
   "                      !        xxxxx            xx!xs              o   o    xx                              xx!x  ",
   "                      !         xxx              x!xxx                      xx                xxxxxxxxxxxxxxx!!x  ",
   "                      !          x               xvx               x   x    xxxxxxx        !!!!!!!!!!!!!!!!!!!xx  ",
   "                      !                                      xx  |   |   |  xx    x       xxx!!!xxxxxxxxxxxxxxx   ",
   "                      !                                  xxxxxxx!!!!!!!!!!!xx            v   !!!                  ",
   "                      !                                  x     xxxx!!!!!xxxx                 !!!                  ",
   "                      !                        x     x   x        xxx!xxx        xxx         xxx                  ",
   "                      !                        x  v  x               !           x x         x x                  ",
   "                      x                        x     x               !             x     v   x                    ",
   "   p                  x                        x     x               !             xx        x                    ",
   "xxxxxxxxx             x                        xx    x               !             x         x                    ",
   "                  o   x                        x  v  x         o     !   x         x         x                    ",
   "               xxxxxxxx       xxx   xxx        x     x               ! o x         x     v   x                    ",
   "              xx     xx         x   x          x     x        xxx    !   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               !   x   x               x                    ",
   "     @       x         x        x   x          x     x               ! p x   x               x                    ",
   "    xxx      x         x        x   x          x     xp              xxxxxxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     xx                    s     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x                           x x        ox                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x                xxxxxxxxxxxx xx       xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!!       xx              xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!x!                        xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx!                                                     ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx !                                                     ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  !                                                     "],    
  ["                                                                                               x!!!!!!!!!!!!!!",
   "                                                                                               x!!!!!!!!!!!!!!",
   "                                                                                               x!!!!!!!!!!!!!!",
   "                                                                                               x!!!!!!!!!!!!!!",
   "                                                                                               x!!!!!!!!!!!!!!",
   "                                        s                                                      x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                                                                        x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                 x                                                      x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                 x                                                      x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                 x                                             s        x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                 x                             !!!            xxxx      x!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!                 xx                             x                x      xv   v    v   v",
   "xxxxxxxxxxxxxxxxxxxxxxx               !!xx                 !!!         x=           =   x      x              ",
   "           xxxxxxxxxxxx               !!xx                 !x!         x     >          x     xx              ",
   "                xxxxx                 xxxxxx                x          x!!!!!!!!!!!!!!!!x      x              ",
   "                 xxx                  x   x                 x   ssss   xxxxxxxxxxxxxxxxxxx     x              ",
   "           xx     x       s           x   x                 x          x                x      x              ",
   "           !!             x           x   x                 xxxxxxxxxxx                       xx              ",
   "           !!                         x   xx      x   x      x                                 x              ",
   "o    b     !!                         x   xxxxxxxxx   xxxxxxxx                x                x              ",
   "x          !!             !           x   x           x                    x!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x          !!             x       >   x   x           x                     xxx                               ",
   "x          !!                       s x   xx          x                                                       ",
   "x          !!    s                  x x   x= = = =    x         s                                             ",
   "x          xxxxxxxxxxxxx              x   x           x                                                       ",
   "     >     xxxxxxxxxxxxx              x   x    = = = =x     s                                                 ",
   " s                     xxxxxxxxxxxxxxxx   xx          x                                                       ",
   "  @                                   x   x           x     xx       x >  x                                   ",
   "xxxxxxxxxxxxxxxx                     sx   x           x              x            x                           ",
   "!!!!!!!!!!!!!!!!                     xxxxxxx     s s  x!!!!!!!!!!!!!!x                                        ",
   "vxxxxxxxxxxxxxxv                           x          x!!!!!!!!!!!!!!!xxxxxxxxxxxxx                           ",
   "         x          xx                   s x   xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!x                           ",
   "  s      xs        x!!xx   xxxxxxxxxxxxxxxxx                          xxxxxxxxxxxxx                        s  ",
   "xxxxx    xx        x!!xx                  x                                      !x                      xxxxx",
   "x        x         x!!xxs                 x                                      !x                      x!x!x",
   "x        x         x!xxxx                 xxxxxxx                        xxxxx   !xs                      !x! ",
   "x      xxxxxxxxxxxxx!xxxxxxxx!!xxxxxx     x                              x!!!x     x                      !x! ",
   "xx                                       xx                             sxvx!x                            !x! ",
   "  xx                                      x       |xxxx|    |xxxx|     xxx xxx                            !x! ",
   "  x                                s s    x                              x                                !x! ",
   "  x s           = xxxxx =     xx          x                             xx         s                      !x! ",
   "  xxxxx           sx!xs       x    xxx    x                             x xs       x   >             >    !x! ",
   "  x                xxx        xxxxxxxxxxxxx  x ss x    x ss x    x ss  xx xx                              !x! ",
   "  x                 x         x           x!!x    x!!!!x    x!!!!x    xx   xx                             !x! ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],*/
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxxxxxxxxxxxxxxxxxxxxxxx                                                       ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "  xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                          x                  x                 ",
   "  x                                                                                                           ",
   "  x                                                              ||                                           ",
   "  x                                                                                                           ",
   "  x                                                                                       x                   ",
   "  x             o          o          o                   ||                  x     x                         ",
   "  x  @                                                                                                       ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x>   >    >     >  x  >     >     >   x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
